wandb_project: sponsor-detect
do_train: True
output_dir: results/transformer
max_seq_len: 50
report_to: all
task_name:
model: distilbert-base-uncased
train:
  train_batchsize: 4
  eval_batchsize: 4
  max_steps: 600
  logging_steps: 10
  eval_steps: 250
  gradient_accumulation_steps: 4
  save_total_limit: 2
  amp: True
  epochs: 1
test:
  batch_size: 4